import type { Template } from "@/lib/firebase/schema";

const LIKERT5_LABELS = ["전혀 그렇지 않다", "그렇지 않다", "보통이다", "그렇다", "매우 그렇다"];
const SCALE = { min: 1, max: 5, labels: LIKERT5_LABELS };

const t = (
  id: string,
  name: string,
  category: Template["category"],
  questions: Template["questions"],
  tags: string[]
): Template => ({
  id,
  name,
  category,
  source: "사용자제공",
  isOfficial: false,
  questions,
  usageCount: 0,
  tags,
});

export const PARENT_TEMPLATES: Template[] = [
  // 1. 1학기 학부모 만족도
  t(
    "parent-01-satisfaction-h1",
    "1학기 학부모 만족도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description:
          "안녕하세요, 학부모님. 1학기 학교 교육활동 전반에 대한 의견을 듣고자 설문을 실시합니다. 응답 결과는 2학기 운영 개선 자료로만 활용되며 약 5분 정도 소요됩니다. 솔직한 답변을 부탁드립니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "1학기 학교 교육활동 전반에 만족합니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "담임 선생님의 학급 운영에 만족합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "학교는 자녀의 학습에 도움을 주고 있다고 생각합니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "학교는 자녀의 생활지도와 인성교육에 힘쓰고 있습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "학교의 안전관리(통학로, 교내 안전 등)에 만족합니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "학교는 학부모와 원활히 소통하고 있습니다.", required: true, scale: SCALE },
      { id: "q7", type: "likert5", title: "1학기 동안 자녀가 학교 생활을 즐겁게 하였다고 느낍니다.", required: true, scale: SCALE },
      { id: "q8", type: "long", title: "1학기 운영에서 잘된 점이나 개선이 필요한 점을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "1학기", "만족도"]
  ),
  // 2. 학년말 학부모 만족도
  t(
    "parent-02-satisfaction-year-end",
    "학년말 학부모 만족도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description:
          "한 해 동안 학교 교육활동에 협조해 주셔서 감사합니다. 학년말을 맞아 학부모님의 종합적인 의견을 수렴하여 다음 학년도 운영 계획에 반영하고자 합니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "올 한 해 자녀의 학교 생활에 전반적으로 만족합니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "올 한 해 담임 선생님의 지도에 만족합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "학교의 교육과정이 자녀 성장에 도움이 되었다고 생각합니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "학교의 생활지도와 인성교육에 만족합니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "학교의 학습 지원(평가·피드백·보충학습)에 만족합니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "학교 행사 및 체험활동 운영에 만족합니다.", required: true, scale: SCALE },
      { id: "q7", type: "likert5", title: "내년에도 우리 학교를 추천하고 싶습니다.", required: true, scale: SCALE },
      { id: "q8", type: "long", title: "다음 학년도에 학교가 더 잘했으면 하는 점이 있다면 적어주세요.", required: false },
      { id: "q9", type: "long", title: "올 한 해 학교에 감사드리고 싶은 점이 있다면 적어주세요.", required: false },
    ],
    ["학부모", "학년말", "만족도"]
  ),
  // 3. 담임교사 소통 만족도
  t(
    "parent-03-homeroom-communication",
    "담임교사 소통 만족도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description:
          "담임 선생님과의 소통 방식에 대한 학부모님의 의견을 수렴하여 더 나은 소통 환경을 만들고자 합니다. 응답은 익명으로 처리됩니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "담임 선생님과의 소통이 원활합니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "담임 선생님께서 학부모의 문의에 신속히 응답해 주십니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "자녀의 학교 생활에 대한 정보를 충분히 안내받습니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "담임 선생님과의 상담이 도움이 됩니다.", required: true, scale: SCALE },
      {
        id: "q5",
        type: "single",
        title: "담임 선생님과 가장 선호하는 소통 방법은 무엇인가요?",
        required: true,
        options: [
          { id: "o1", label: "학교 알림장 앱(하이클래스, 클래스팅 등)" },
          { id: "o2", label: "전화" },
          { id: "o3", label: "문자/카카오톡" },
          { id: "o4", label: "대면 상담" },
          { id: "o5", label: "이메일" },
        ],
      },
      {
        id: "q6",
        type: "single",
        title: "현재 받고 있는 소통 빈도는 어떻습니까?",
        required: true,
        options: [
          { id: "o1", label: "너무 적다" },
          { id: "o2", label: "적은 편이다" },
          { id: "o3", label: "적당하다" },
          { id: "o4", label: "많은 편이다" },
          { id: "o5", label: "너무 많다" },
        ],
      },
      { id: "q7", type: "long", title: "담임 선생님과의 소통에 대해 건의하실 사항이 있다면 적어주세요.", required: false },
    ],
    ["학부모", "담임", "소통"]
  ),
  // 4. 학교 시설 만족도
  t(
    "parent-04-facility-satisfaction",
    "학교 시설 만족도 조사(학부모)",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교 시설 환경 개선을 위해 학부모님의 의견을 수렴합니다. 자녀를 통해 들으셨거나 직접 방문 시 느끼신 점을 바탕으로 응답해 주세요.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "학교 건물(교실, 복도) 환경이 깨끗하고 쾌적합니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "화장실 위생 및 관리 상태가 양호합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "운동장 및 체육 시설이 안전하고 잘 관리되어 있습니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "도서관(도서실)이 잘 운영되고 있습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "급식실 환경이 위생적이고 쾌적합니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "냉난방 시설이 적절히 운영되고 있습니다.", required: true, scale: SCALE },
      { id: "q7", type: "likert5", title: "학교 안전시설(CCTV, 비상구, 소방 등)이 잘 갖춰져 있습니다.", required: true, scale: SCALE },
      {
        id: "q8",
        type: "multiple",
        title: "가장 시급히 개선이 필요한 시설은 무엇입니까? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "화장실" },
          { id: "o2", label: "교실 환경" },
          { id: "o3", label: "운동장/체육시설" },
          { id: "o4", label: "냉난방" },
          { id: "o5", label: "급식실" },
          { id: "o6", label: "도서관" },
          { id: "o7", label: "통학로/주차장" },
        ],
      },
      { id: "q9", type: "long", title: "시설 개선과 관련하여 건의하실 사항을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "시설", "환경"]
  ),
  // 5. 급식 만족도(학부모)
  t(
    "parent-05-meal-satisfaction",
    "급식 만족도 조사(학부모)",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교 급식 운영 개선을 위해 학부모님의 의견을 수렴합니다. 자녀로부터 들은 내용 또는 식단표를 보고 느끼신 점을 토대로 응답해 주세요.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "자녀가 학교 급식에 만족한다고 이야기합니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "급식 식단이 영양적으로 균형 있게 구성되어 있습니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "급식의 위생과 안전 관리에 신뢰가 갑니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "월별 식단표 안내가 잘 이루어집니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "알레르기 정보 및 원산지 표기가 명확합니다.", required: true, scale: SCALE },
      {
        id: "q6",
        type: "single",
        title: "자녀가 학교에서 급식을 어느 정도 잘 먹는다고 들으셨나요?",
        required: true,
        options: [
          { id: "o1", label: "거의 다 먹는다" },
          { id: "o2", label: "절반 이상 먹는다" },
          { id: "o3", label: "절반 정도 먹는다" },
          { id: "o4", label: "조금 먹는다" },
          { id: "o5", label: "거의 먹지 않는다" },
        ],
      },
      { id: "q7", type: "long", title: "자녀가 좋아한다고 말한 급식 메뉴가 있다면 알려주세요.", required: false },
      { id: "q8", type: "long", title: "급식 운영에 대한 건의사항을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "급식", "영양"]
  ),
  // 6. 방과후 프로그램 만족도(학부모)
  t(
    "parent-06-afterschool-satisfaction",
    "방과후 프로그램 만족도 조사(학부모)",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "방과후 프로그램의 질적 개선을 위해 학부모님의 의견을 수렴합니다. 자녀가 참여 중인 프로그램을 떠올리며 응답해 주세요.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "방과후 프로그램 종류가 다양하게 개설되어 있습니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "프로그램 운영 시간과 일정이 적절합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "방과후 강사의 전문성과 지도에 만족합니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "수강료가 합리적인 수준입니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "자녀가 방과후 프로그램을 즐겁게 참여하고 있습니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "프로그램 신청·결제·환불 절차가 편리합니다.", required: true, scale: SCALE },
      {
        id: "q7",
        type: "multiple",
        title: "추가로 개설되었으면 하는 프로그램 분야는 무엇입니까? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "체육/스포츠" },
          { id: "o2", label: "예술(미술, 음악)" },
          { id: "o3", label: "코딩/AI/로봇" },
          { id: "o4", label: "외국어(영어 등)" },
          { id: "o5", label: "독서/논술" },
          { id: "o6", label: "수학/과학" },
          { id: "o7", label: "요리/생활" },
        ],
      },
      { id: "q8", type: "long", title: "방과후 프로그램에 대한 건의사항을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "방과후", "만족도"]
  ),
  // 7. 가정통신문 도착·내용 만족도
  t(
    "parent-07-newsletter-satisfaction",
    "가정통신문 도착·내용 만족도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "가정통신문 운영 개선을 위해 학부모님의 의견을 수렴합니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "가정통신문이 제때 도착(전달)됩니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "가정통신문의 내용이 이해하기 쉽고 명확합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "가정통신문의 분량이 적절합니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "회신이 필요한 내용은 회신 방법이 명확하게 안내됩니다.", required: true, scale: SCALE },
      {
        id: "q5",
        type: "single",
        title: "가정통신문을 가장 자주 받아보시는 경로는 무엇입니까?",
        required: true,
        options: [
          { id: "o1", label: "종이(자녀가 가져옴)" },
          { id: "o2", label: "학교 알림장 앱" },
          { id: "o3", label: "학교 홈페이지" },
          { id: "o4", label: "문자/카카오톡" },
          { id: "o5", label: "이메일" },
        ],
      },
      {
        id: "q6",
        type: "single",
        title: "선호하시는 가정통신문 전달 방식은 무엇입니까?",
        required: true,
        options: [
          { id: "o1", label: "종이만" },
          { id: "o2", label: "전자(앱·문자)만" },
          { id: "o3", label: "종이와 전자 병행" },
        ],
      },
      { id: "q7", type: "long", title: "가정통신문에 대한 의견을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "가정통신문", "소통"]
  ),
  // 8. 학부모 총회 참여 의향
  t(
    "parent-08-general-meeting",
    "학부모 총회 참여 의향 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description:
          "학부모 총회 운영 계획 수립에 참고하고자 학부모님의 참여 의향을 조사합니다. 응답해 주신 내용은 일정 및 운영 방식 결정에 활용됩니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "올해 학부모 총회에 참석할 의향이 있으신가요?",
        required: true,
        options: [
          { id: "o1", label: "반드시 참석" },
          { id: "o2", label: "가능하면 참석" },
          { id: "o3", label: "잘 모르겠음" },
          { id: "o4", label: "참석 어려움" },
        ],
      },
      {
        id: "q2",
        type: "single",
        title: "선호하시는 총회 진행 방식은 무엇입니까?",
        required: true,
        options: [
          { id: "o1", label: "대면 참석" },
          { id: "o2", label: "온라인(Zoom 등)" },
          { id: "o3", label: "대면·온라인 동시" },
        ],
      },
      {
        id: "q3",
        type: "single",
        title: "선호하시는 시간대는 언제입니까?",
        required: true,
        options: [
          { id: "o1", label: "평일 오전" },
          { id: "o2", label: "평일 오후(하교 직후)" },
          { id: "o3", label: "평일 저녁(18시 이후)" },
          { id: "o4", label: "토요일 오전" },
        ],
      },
      {
        id: "q4",
        type: "multiple",
        title: "총회에서 가장 듣고 싶은 내용은 무엇입니까? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "학교 교육과정 안내" },
          { id: "o2", label: "학년·학급 운영 계획" },
          { id: "o3", label: "생활지도 방향" },
          { id: "o4", label: "평가 방법" },
          { id: "o5", label: "학교폭력 예방" },
          { id: "o6", label: "학부모회·학교운영위원회 안내" },
        ],
      },
      {
        id: "q5",
        type: "single",
        title: "총회 참여가 어려운 가장 큰 이유는 무엇입니까?",
        required: false,
        options: [
          { id: "o1", label: "직장 근무" },
          { id: "o2", label: "동생 돌봄" },
          { id: "o3", label: "거리/교통" },
          { id: "o4", label: "관심 부족" },
          { id: "o5", label: "기타" },
        ],
      },
      { id: "q6", type: "long", title: "학부모 총회 운영에 바라는 점이 있다면 적어주세요.", required: false },
    ],
    ["학부모", "총회", "참여"]
  ),
  // 9. 학부모 동아리 참여
  t(
    "parent-09-club-participation",
    "학부모 동아리 참여 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학부모 동아리 운영 활성화를 위해 의견을 수렴합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "학부모 동아리 활동에 참여할 의향이 있으십니까?",
        required: true,
        options: [
          { id: "o1", label: "매우 있다" },
          { id: "o2", label: "있다" },
          { id: "o3", label: "보통" },
          { id: "o4", label: "별로 없다" },
          { id: "o5", label: "전혀 없다" },
        ],
      },
      {
        id: "q2",
        type: "multiple",
        title: "관심 있는 동아리 분야는 무엇입니까? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "독서/책읽기" },
          { id: "o2", label: "운동/요가/걷기" },
          { id: "o3", label: "공예/미술" },
          { id: "o4", label: "요리/제과" },
          { id: "o5", label: "교육 봉사(독서 도우미 등)" },
          { id: "o6", label: "환경·녹색가꾸기" },
          { id: "o7", label: "학부모 자율 학습(영어, 디지털 등)" },
        ],
      },
      {
        id: "q3",
        type: "single",
        title: "선호하시는 활동 빈도는 어떻습니까?",
        required: true,
        options: [
          { id: "o1", label: "주 1회" },
          { id: "o2", label: "격주 1회" },
          { id: "o3", label: "월 1회" },
          { id: "o4", label: "분기 1회" },
        ],
      },
      {
        id: "q4",
        type: "single",
        title: "선호하시는 활동 시간대는 언제입니까?",
        required: true,
        options: [
          { id: "o1", label: "평일 오전" },
          { id: "o2", label: "평일 오후" },
          { id: "o3", label: "평일 저녁" },
          { id: "o4", label: "주말" },
        ],
      },
      { id: "q5", type: "likert5", title: "학부모 동아리가 학교 공동체 형성에 도움이 된다고 생각합니다.", required: true, scale: SCALE },
      { id: "q6", type: "long", title: "운영하고 싶은 동아리 또는 건의사항이 있다면 적어주세요.", required: false },
    ],
    ["학부모", "동아리", "공동체"]
  ),
  // 10. 학부모 상담 주간 운영 만족도
  t(
    "parent-10-counseling-week",
    "학부모 상담 주간 운영 만족도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학부모 상담 주간 운영의 개선을 위해 의견을 수렴합니다. 상담에 참여하신 학부모님께서 응답해 주시기 바랍니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "이번 학부모 상담에 참여하셨습니까?",
        required: true,
        options: [
          { id: "o1", label: "예" },
          { id: "o2", label: "아니오" },
        ],
      },
      { id: "q2", type: "likert5", title: "상담 신청 절차가 편리했습니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "상담 시간 배정이 적절했습니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "담임 선생님이 상담을 충분히 준비하셨습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "상담을 통해 자녀의 학교 생활에 대해 충분히 이해할 수 있었습니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "상담 환경(장소, 분위기)이 편안했습니다.", required: true, scale: SCALE },
      {
        id: "q7",
        type: "single",
        title: "선호하시는 상담 방식은 무엇입니까?",
        required: false,
        options: [
          { id: "o1", label: "대면 상담" },
          { id: "o2", label: "전화 상담" },
          { id: "o3", label: "화상 상담(Zoom 등)" },
          { id: "o4", label: "선택 가능(혼합)" },
        ],
      },
      { id: "q8", type: "long", title: "상담 주간 운영에 대한 건의사항을 적어주세요.", required: false },
    ],
    ["학부모", "상담", "운영"]
  ),
  // 11. 학교폭력 예방교육 인식
  t(
    "parent-11-violence-prevention",
    "학교폭력 예방교육 인식 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교폭력 예방을 위한 학교의 노력에 대한 학부모님의 인식을 조사합니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "학교는 학교폭력 예방을 위해 노력하고 있다고 생각합니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "자녀에게 학교폭력 예방교육이 충분히 이루어지고 있습니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "학교폭력 사안 발생 시 학교의 대응을 신뢰합니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "학교폭력 신고·상담 창구가 잘 안내되어 있습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "자녀가 학교에서 안전하다고 느낀다고 생각합니다.", required: true, scale: SCALE },
      {
        id: "q6",
        type: "single",
        title: "최근 1년간 자녀가 학교폭력(신체·언어·사이버 등)을 겪거나 목격한 적이 있다고 들으셨나요?",
        required: true,
        options: [
          { id: "o1", label: "전혀 없음" },
          { id: "o2", label: "들어본 적 있음(목격)" },
          { id: "o3", label: "직접 겪었다고 들음" },
          { id: "o4", label: "잘 모름" },
        ],
      },
      {
        id: "q7",
        type: "multiple",
        title: "학교가 강화해야 할 예방교육 영역은 무엇이라고 생각하십니까? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "사이버폭력(SNS, 단톡방)" },
          { id: "o2", label: "언어폭력·따돌림" },
          { id: "o3", label: "신체폭력" },
          { id: "o4", label: "성인지 감수성" },
          { id: "o5", label: "방관자 교육" },
          { id: "o6", label: "회복적 생활교육" },
        ],
      },
      { id: "q8", type: "long", title: "학교폭력 예방을 위해 건의하실 사항을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "학교폭력", "예방"]
  ),
  // 12. 자녀 가정학습 환경
  t(
    "parent-12-home-learning-env",
    "자녀 가정학습 환경 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "자녀의 가정학습 환경을 점검하여 학교의 학습 지도 방향을 정립하는 데 활용하고자 합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "자녀에게 별도의 학습 공간(책상)이 마련되어 있습니까?",
        required: true,
        options: [
          { id: "o1", label: "독립된 방과 책상" },
          { id: "o2", label: "공용 공간에 자녀 전용 책상" },
          { id: "o3", label: "거실/식탁 등 공용 공간 사용" },
          { id: "o4", label: "마련되어 있지 않음" },
        ],
      },
      { id: "q2", type: "likert5", title: "자녀는 가정에서 스스로 학습하는 습관이 있습니다.", required: true, scale: SCALE },
      {
        id: "q3",
        type: "single",
        title: "자녀의 평일 평균 가정학습 시간(학원 제외)은 어느 정도입니까?",
        required: true,
        options: [
          { id: "o1", label: "30분 미만" },
          { id: "o2", label: "30분~1시간" },
          { id: "o3", label: "1~2시간" },
          { id: "o4", label: "2~3시간" },
          { id: "o5", label: "3시간 이상" },
        ],
      },
      { id: "q4", type: "likert5", title: "자녀의 학습을 부모(보호자)가 지도하거나 함께 봐줄 수 있습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "가정에 학습에 필요한 도서·자료가 충분히 있습니다.", required: true, scale: SCALE },
      {
        id: "q6",
        type: "single",
        title: "가정에 자녀가 사용할 수 있는 디지털 학습기기(노트북·태블릿 등)가 있습니까?",
        required: true,
        options: [
          { id: "o1", label: "자녀 전용 기기 있음" },
          { id: "o2", label: "가족 공용 기기 있음" },
          { id: "o3", label: "없음" },
        ],
      },
      { id: "q7", type: "long", title: "가정학습에서 가장 어려운 점은 무엇입니까?", required: false },
    ],
    ["학부모", "가정학습", "환경"]
  ),
  // 13. 자녀 스마트폰·미디어 사용 시간
  t(
    "parent-13-media-usage",
    "자녀 스마트폰·미디어 사용 시간 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "자녀의 미디어 사용 실태를 파악하여 미디어 리터러시 교육 방향을 수립하고자 합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "자녀가 본인 명의(또는 전용)의 스마트폰을 가지고 있습니까?",
        required: true,
        options: [
          { id: "o1", label: "예, 본인 전용" },
          { id: "o2", label: "공용(가족과 공유)" },
          { id: "o3", label: "없음" },
        ],
      },
      {
        id: "q2",
        type: "single",
        title: "자녀의 평일 하루 평균 스마트폰·태블릿 사용 시간(학습 제외)은?",
        required: true,
        options: [
          { id: "o1", label: "1시간 미만" },
          { id: "o2", label: "1~2시간" },
          { id: "o3", label: "2~3시간" },
          { id: "o4", label: "3~4시간" },
          { id: "o5", label: "4시간 이상" },
        ],
      },
      {
        id: "q3",
        type: "multiple",
        title: "자녀가 주로 사용하는 콘텐츠는 무엇입니까? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "유튜브/영상" },
          { id: "o2", label: "게임" },
          { id: "o3", label: "SNS(인스타·틱톡 등)" },
          { id: "o4", label: "메신저(카톡 등)" },
          { id: "o5", label: "웹툰/만화" },
          { id: "o6", label: "학습 콘텐츠" },
        ],
      },
      { id: "q4", type: "likert5", title: "가정에서 자녀의 미디어 사용 시간에 대한 규칙이 있습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "자녀의 미디어 사용 시간을 조절하는 데 어려움을 느낍니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "자녀의 스마트폰 과의존이 걱정됩니다.", required: true, scale: SCALE },
      { id: "q7", type: "long", title: "자녀의 미디어 사용에 대해 학교에 바라는 교육이 있다면 적어주세요.", required: false },
    ],
    ["학부모", "미디어", "스마트폰"]
  ),
  // 14. 자녀 수면·식습관 가정 관찰
  t(
    "parent-14-sleep-eating",
    "자녀 수면·식습관 가정 관찰 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "자녀의 건강한 생활습관 형성을 위해 가정에서 관찰하신 내용을 조사합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "자녀의 평일 평균 수면 시간은 어느 정도입니까?",
        required: true,
        options: [
          { id: "o1", label: "6시간 미만" },
          { id: "o2", label: "6~7시간" },
          { id: "o3", label: "7~8시간" },
          { id: "o4", label: "8~9시간" },
          { id: "o5", label: "9시간 이상" },
        ],
      },
      {
        id: "q2",
        type: "single",
        title: "자녀의 평일 취침 시간은 대체로 언제입니까?",
        required: true,
        options: [
          { id: "o1", label: "21시 이전" },
          { id: "o2", label: "21~22시" },
          { id: "o3", label: "22~23시" },
          { id: "o4", label: "23~24시" },
          { id: "o5", label: "24시 이후" },
        ],
      },
      { id: "q3", type: "likert5", title: "자녀가 아침 식사를 거의 매일 합니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "자녀의 식습관(편식 등)에 큰 어려움이 없습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "자녀가 충분히 잠을 자고 활기차게 일어납니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "자녀가 가공식품·인스턴트보다 균형 잡힌 식사를 합니다.", required: true, scale: SCALE },
      {
        id: "q7",
        type: "multiple",
        title: "자녀의 생활습관과 관련하여 가장 걱정되는 부분은? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "수면 부족" },
          { id: "o2", label: "늦은 취침" },
          { id: "o3", label: "아침 결식" },
          { id: "o4", label: "편식" },
          { id: "o5", label: "과식/간식 과다" },
          { id: "o6", label: "운동 부족" },
        ],
      },
      { id: "q8", type: "long", title: "자녀의 건강 생활습관 형성에 학교 교육에 바라는 점을 적어주세요.", required: false },
    ],
    ["학부모", "건강", "생활습관"]
  ),
  // 15. 자녀 진로에 대한 부모 인식
  t(
    "parent-15-career-perception",
    "자녀 진로에 대한 부모 인식 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "자녀의 진로 지도 방향 수립을 위해 학부모님의 인식을 조사합니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "자녀의 진로에 대해 평소 충분히 대화합니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "자녀의 적성과 흥미를 잘 알고 있다고 생각합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "자녀가 희망하는 진로를 존중하는 편입니다.", required: true, scale: SCALE },
      {
        id: "q4",
        type: "single",
        title: "자녀의 진로 결정에 가장 중요하다고 생각하는 요소는?",
        required: true,
        options: [
          { id: "o1", label: "자녀의 적성·흥미" },
          { id: "o2", label: "안정성·소득" },
          { id: "o3", label: "사회적 기여" },
          { id: "o4", label: "성적·성취도" },
          { id: "o5", label: "직업의 미래 전망" },
        ],
      },
      {
        id: "q5",
        type: "multiple",
        title: "학교가 강화했으면 하는 진로 활동은? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "직업 체험" },
          { id: "o2", label: "진로 적성 검사" },
          { id: "o3", label: "직업인 초청 강연" },
          { id: "o4", label: "대학·고등학교 탐방" },
          { id: "o5", label: "진로 상담" },
          { id: "o6", label: "진로 관련 동아리" },
        ],
      },
      { id: "q6", type: "likert5", title: "자녀의 진로 지도에 어려움을 느낍니다.", required: true, scale: SCALE },
      { id: "q7", type: "long", title: "자녀 진로 지도에 학교에 바라는 점을 적어주세요.", required: false },
    ],
    ["학부모", "진로", "인식"]
  ),
  // 16. 학교 행사(운동회·축제) 만족도
  t(
    "parent-16-event-satisfaction",
    "학교 행사(운동회·축제) 만족도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교 행사 운영의 개선을 위해 참여하신 학부모님의 의견을 수렴합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "참여하신 학교 행사는 무엇입니까?",
        required: true,
        options: [
          { id: "o1", label: "운동회/체육대회" },
          { id: "o2", label: "학예회/축제" },
          { id: "o3", label: "학습발표회" },
          { id: "o4", label: "졸업식·입학식" },
          { id: "o5", label: "기타" },
        ],
      },
      { id: "q2", type: "likert5", title: "행사 사전 안내가 충분히 이루어졌습니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "행사 진행이 매끄럽고 시간 운영이 적절했습니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "행사 내용이 자녀에게 의미 있고 즐거웠습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "학부모 참여 기회가 적절히 제공되었습니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "행사 안전 관리가 잘 이루어졌습니다.", required: true, scale: SCALE },
      { id: "q7", type: "likert5", title: "전반적으로 학교 행사에 만족합니다.", required: true, scale: SCALE },
      { id: "q8", type: "long", title: "행사 운영에 대한 건의사항을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "행사", "만족도"]
  ),
  // 17. 학교 안전·통학로 인식
  t(
    "parent-17-safety-commute",
    "학교 안전·통학로 인식 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "자녀의 등하굣길과 학교 내 안전에 대한 학부모님의 인식을 조사합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "자녀의 주된 등교 방법은 무엇입니까?",
        required: true,
        options: [
          { id: "o1", label: "도보" },
          { id: "o2", label: "자전거/킥보드" },
          { id: "o3", label: "보호자 차량" },
          { id: "o4", label: "통학버스" },
          { id: "o5", label: "대중교통" },
        ],
      },
      { id: "q2", type: "likert5", title: "자녀의 통학로가 안전하다고 생각합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "통학로 주변 보행자 신호·횡단보도가 잘 갖춰져 있습니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "학교 주변 차량 속도 관리가 잘 이루어집니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "학교 내부(운동장, 복도 등)가 안전하게 관리됩니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "녹색어머니회·교통지도 활동이 적절히 운영됩니다.", required: true, scale: SCALE },
      {
        id: "q7",
        type: "multiple",
        title: "통학로에서 가장 우려되는 위험 요소는? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "차량 속도" },
          { id: "o2", label: "불법 주정차" },
          { id: "o3", label: "신호등·횡단보도 부재" },
          { id: "o4", label: "보행로 미확보" },
          { id: "o5", label: "야간 조도 부족" },
          { id: "o6", label: "공사 구간" },
        ],
      },
      { id: "q8", type: "long", title: "통학로 안전 개선을 위해 건의하실 사항을 적어주세요.", required: false },
    ],
    ["학부모", "안전", "통학로"]
  ),
  // 18. 학교 알림장(앱) 사용 만족도
  t(
    "parent-18-school-app",
    "학교 알림장(앱) 사용 만족도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교 알림장 앱(하이클래스·클래스팅·아이엠스쿨 등) 운영의 개선을 위해 의견을 수렴합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "현재 사용 중인 학교 알림장 앱은 무엇입니까?",
        required: true,
        options: [
          { id: "o1", label: "하이클래스" },
          { id: "o2", label: "클래스팅" },
          { id: "o3", label: "아이엠스쿨" },
          { id: "o4", label: "e알리미" },
          { id: "o5", label: "기타" },
        ],
      },
      { id: "q2", type: "likert5", title: "앱 사용 방법이 쉽고 직관적입니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "공지사항·알림이 제때 전달됩니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "앱의 알림 빈도가 적절합니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "앱을 통해 회신·답장이 편리하게 이루어집니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "앱에서 첨부파일 확인이 원활합니다.", required: true, scale: SCALE },
      { id: "q7", type: "likert5", title: "앱 사용 중 오류·접속 문제가 거의 없습니다.", required: true, scale: SCALE },
      { id: "q8", type: "long", title: "알림장 앱 사용에 대한 건의사항을 적어주세요.", required: false },
    ],
    ["학부모", "앱", "알림장"]
  ),
  // 19. 학년 초 가정환경 조사 (개인정보 동의 포함)
  t(
    "parent-19-family-info",
    "학년 초 가정환경 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "개인정보 수집·이용 안내",
        description:
          "본 조사는 자녀의 학교 생활 지도 및 안전한 학습 환경 조성을 목적으로 실시합니다. 수집된 정보는 담임교사가 교육 목적으로만 활용하며, 학년 종료 후 안전하게 폐기됩니다.\n\n- 수집 항목: 자녀 정보(이름, 생년월일, 형제자매), 보호자 정보(연락처, 직업), 가정 환경(주소, 응급 연락처), 건강 정보(알레르기·복용 약 등)\n- 보유 기간: 해당 학년도 종료 후 1개월 이내 폐기\n- 동의를 거부하실 권리가 있으며, 다만 비상 연락 등 일부 지원이 제한될 수 있습니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "위 개인정보 수집·이용에 동의하십니까?",
        required: true,
        options: [
          { id: "o1", label: "동의합니다" },
          { id: "o2", label: "동의하지 않습니다" },
        ],
      },
      { id: "q2", type: "short", title: "자녀의 이름을 입력해 주세요.", required: true },
      { id: "q3", type: "short", title: "자녀의 생년월일(YYYY-MM-DD)을 입력해 주세요.", required: true },
      { id: "q4", type: "short", title: "보호자(주연락처) 이름과 자녀와의 관계를 입력해 주세요.", required: true },
      { id: "q5", type: "short", title: "주연락처(휴대전화)를 입력해 주세요.", required: true },
      { id: "q6", type: "short", title: "비상 연락처(가족 등)를 입력해 주세요.", required: false },
      { id: "q7", type: "short", title: "현재 거주지(시·구·동)를 입력해 주세요.", required: true },
      {
        id: "q8",
        type: "single",
        title: "가족 구성은 어떻게 됩니까?",
        required: false,
        options: [
          { id: "o1", label: "양친 가족" },
          { id: "o2", label: "한부모 가족" },
          { id: "o3", label: "조손 가족" },
          { id: "o4", label: "기타" },
        ],
      },
      { id: "q9", type: "long", title: "자녀의 건강 특이사항(알레르기, 복용 약, 지병 등)이 있다면 적어주세요.", required: false },
      { id: "q10", type: "long", title: "담임 선생님께 미리 알리고 싶은 자녀의 특성·요청사항을 적어주세요.", required: false },
    ],
    ["학부모", "가정환경", "학년초"]
  ),
  // 20. 자녀 친구관계에 대한 부모 인식
  t(
    "parent-20-friendship-perception",
    "자녀 친구관계에 대한 부모 인식 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "자녀의 또래관계와 사회성 발달에 대한 학부모님의 관찰을 조사합니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "자녀가 학교에서 친한 친구가 있다고 들었습니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "자녀가 친구들과 잘 어울린다고 생각합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "자녀가 학교 친구 이야기를 자주 하는 편입니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "자녀가 친구 관계로 스트레스를 받는다고 느낍니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "자녀가 새로운 친구를 사귀는 데 어려움이 없습니다.", required: true, scale: SCALE },
      {
        id: "q6",
        type: "single",
        title: "자녀와 친구 관계에 대해 얼마나 자주 대화하십니까?",
        required: true,
        options: [
          { id: "o1", label: "거의 매일" },
          { id: "o2", label: "주 2~3회" },
          { id: "o3", label: "주 1회 정도" },
          { id: "o4", label: "월 1~2회" },
          { id: "o5", label: "거의 안 함" },
        ],
      },
      {
        id: "q7",
        type: "multiple",
        title: "자녀의 또래관계에서 가장 우려되는 부분은? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "친한 친구 부재" },
          { id: "o2", label: "따돌림 가능성" },
          { id: "o3", label: "갈등 해결 미숙" },
          { id: "o4", label: "SNS·단톡방 갈등" },
          { id: "o5", label: "지나친 친구 의존" },
        ],
      },
      { id: "q8", type: "long", title: "자녀의 친구관계와 관련하여 학교에 도움을 요청하실 사항이 있다면 적어주세요.", required: false },
    ],
    ["학부모", "친구관계", "사회성"]
  ),
  // 21. 가정 내 학습지도 어려움
  t(
    "parent-21-home-tutoring-difficulty",
    "가정 내 학습지도 어려움 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "가정에서 자녀의 학습을 지도하실 때 겪으시는 어려움을 파악하여 학교의 학습 지원 방향을 수립하고자 합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "자녀의 학습을 가정에서 직접 지도하시는 빈도는?",
        required: true,
        options: [
          { id: "o1", label: "거의 매일" },
          { id: "o2", label: "주 3~4회" },
          { id: "o3", label: "주 1~2회" },
          { id: "o4", label: "거의 안 함" },
        ],
      },
      { id: "q2", type: "likert5", title: "자녀의 학습 내용(교과서·과제)을 어느 정도 이해하고 지도할 수 있습니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "자녀의 학습 동기를 끌어내는 데 어려움을 느낍니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "자녀의 학습 과정에서 감정적 갈등이 생기곤 합니다.", required: true, scale: SCALE },
      {
        id: "q5",
        type: "multiple",
        title: "가정학습 지도에서 가장 어려운 점은? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "교과 내용을 모르겠다" },
          { id: "o2", label: "지도할 시간이 부족하다" },
          { id: "o3", label: "자녀가 협조하지 않는다" },
          { id: "o4", label: "감정 조절이 어렵다" },
          { id: "o5", label: "어떻게 가르쳐야 할지 모른다" },
          { id: "o6", label: "동생 돌봄 등 환경적 어려움" },
        ],
      },
      {
        id: "q6",
        type: "multiple",
        title: "학교가 제공하면 도움이 될 학부모 학습 지원은? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "교과 학습 안내자료" },
          { id: "o2", label: "학부모 대상 학습코칭 강의" },
          { id: "o3", label: "온라인 학습 콘텐츠 안내" },
          { id: "o4", label: "단원평가 결과 상세 피드백" },
          { id: "o5", label: "방과후 보충학습 운영" },
        ],
      },
      { id: "q7", type: "long", title: "가정학습 지도와 관련하여 학교에 바라는 점을 적어주세요.", required: false },
    ],
    ["학부모", "학습지도", "어려움"]
  ),
  // 22. 학부모 교육 프로그램 요구도
  t(
    "parent-22-parent-edu-needs",
    "학부모 교육 프로그램 요구도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학부모님께 도움이 될 교육 프로그램을 운영하고자 요구도를 조사합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "학부모 교육 프로그램에 참여한 경험이 있으십니까?",
        required: true,
        options: [
          { id: "o1", label: "매년 참여한다" },
          { id: "o2", label: "가끔 참여한다" },
          { id: "o3", label: "거의 참여하지 않는다" },
          { id: "o4", label: "참여한 적 없다" },
        ],
      },
      {
        id: "q2",
        type: "multiple",
        title: "관심 있는 학부모 교육 주제를 모두 선택해 주세요. (복수 선택)",
        required: true,
        options: [
          { id: "o1", label: "자녀와의 대화법·관계" },
          { id: "o2", label: "사춘기 자녀 이해" },
          { id: "o3", label: "미디어·스마트폰 지도" },
          { id: "o4", label: "학습 코칭" },
          { id: "o5", label: "진로·진학 정보" },
          { id: "o6", label: "정서·심리 이해(불안, ADHD 등)" },
          { id: "o7", label: "학교폭력 예방·대처" },
          { id: "o8", label: "성교육·성인지 감수성" },
        ],
      },
      {
        id: "q3",
        type: "single",
        title: "선호하는 운영 방식은?",
        required: true,
        options: [
          { id: "o1", label: "대면 강의" },
          { id: "o2", label: "온라인 실시간(Zoom 등)" },
          { id: "o3", label: "녹화 영상(언제든 시청)" },
          { id: "o4", label: "워크숍·소그룹 토론" },
        ],
      },
      {
        id: "q4",
        type: "single",
        title: "선호하는 시간대는?",
        required: true,
        options: [
          { id: "o1", label: "평일 오전" },
          { id: "o2", label: "평일 오후" },
          { id: "o3", label: "평일 저녁" },
          { id: "o4", label: "주말" },
        ],
      },
      { id: "q5", type: "likert5", title: "학부모 교육 프로그램이 자녀 양육에 도움이 된다고 생각합니다.", required: true, scale: SCALE },
      { id: "q6", type: "long", title: "추가로 듣고 싶은 강의 주제가 있다면 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "교육", "요구도"]
  ),
  // 23. 다문화 가정 학교생활 의견
  t(
    "parent-23-multicultural-opinion",
    "다문화 가정 학교생활 의견 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description:
          "다문화 가정 자녀의 학교생활을 지원하기 위해 학부모님의 의견을 수렴합니다. 응답은 익명으로 처리되며 지원 정책 수립에 활용됩니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "자녀가 학교생활에 잘 적응하고 있다고 느낍니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "학교에서 자녀가 차별이나 소외감 없이 지내고 있다고 생각합니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "학교의 가정통신문·안내가 이해하기 쉬운 한국어로 제공됩니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "담임 선생님과의 소통에 어려움이 없습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "학교의 한국어 학습 지원(KSL 등)에 만족합니다.", required: true, scale: SCALE },
      {
        id: "q6",
        type: "multiple",
        title: "학교에서 추가로 지원해 주면 도움이 될 부분은? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "한국어 학습 지원" },
          { id: "o2", label: "통역·번역 안내" },
          { id: "o3", label: "다문화 이해 교육" },
          { id: "o4", label: "학습 멘토링" },
          { id: "o5", label: "학부모 대상 한국어 교실" },
          { id: "o6", label: "지역사회 연계 프로그램" },
        ],
      },
      { id: "q7", type: "long", title: "자녀의 학교생활 적응 또는 학부모 본인의 학교 참여에 대해 건의하실 사항을 적어주세요.", required: false },
    ],
    ["학부모", "다문화", "지원"]
  ),
  // 24. 특수교육 통합학급 만족도
  t(
    "parent-24-inclusive-edu",
    "특수교육 통합학급 운영 만족도 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description:
          "통합학급 운영의 개선을 위해 통합학급 학생(특수교육 대상 학생 및 일반 학생) 학부모님의 의견을 수렴합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "응답하시는 학부모님의 자녀는 어디에 해당합니까?",
        required: true,
        options: [
          { id: "o1", label: "특수교육 대상 학생 학부모" },
          { id: "o2", label: "통합학급 일반 학생 학부모" },
        ],
      },
      { id: "q2", type: "likert5", title: "통합학급 운영에 대해 학교의 안내가 충분히 이루어졌습니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "담임교사와 특수교사의 협력이 잘 이루어진다고 느낍니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "자녀가 통합학급에서 잘 적응하고 있다고 생각합니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "통합학급 친구들 간의 상호작용이 긍정적이라고 느낍니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "학교의 장애 이해 교육이 잘 이루어지고 있습니다.", required: true, scale: SCALE },
      { id: "q7", type: "likert5", title: "통합학급 운영에 대해 전반적으로 만족합니다.", required: true, scale: SCALE },
      { id: "q8", type: "long", title: "통합학급 운영 개선을 위해 건의하실 사항을 적어주세요.", required: false },
    ],
    ["학부모", "특수교육", "통합학급"]
  ),
  // 25. 학교 평가 학부모 의견
  t(
    "parent-25-school-evaluation",
    "학교 평가 학부모 의견 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교 자체 평가를 위해 학부모님의 종합적인 의견을 수렴합니다. 결과는 학교 운영 개선과 학교 평가 보고서에 반영됩니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "학교의 교육 목표·방침이 잘 안내되어 있습니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "학교 교육과정 운영이 자녀의 성장에 도움이 됩니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "학교는 학부모 의견을 적극 반영하려 노력합니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "학교는 민주적이고 투명하게 운영되고 있습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "학교는 학생 인권을 존중하고 있습니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "학교는 지역사회와 잘 연계하여 운영됩니다.", required: true, scale: SCALE },
      { id: "q7", type: "likert5", title: "전반적으로 우리 학교를 신뢰하고 만족합니다.", required: true, scale: SCALE },
      { id: "q8", type: "long", title: "학교 평가에 반영했으면 하는 의견·건의사항을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "학교평가", "운영"]
  ),
  // 26. 자녀 교복·학용품 부담
  t(
    "parent-26-uniform-supplies-burden",
    "자녀 교복·학용품 부담 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "자녀 교육에 따른 교복·학용품 등 경제적 부담 정도를 파악하여 지원 방안을 모색하고자 합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "교복(체육복 포함) 비용에 대해 어떻게 느끼십니까?",
        required: false,
        options: [
          { id: "o1", label: "전혀 부담되지 않음" },
          { id: "o2", label: "약간 부담" },
          { id: "o3", label: "보통" },
          { id: "o4", label: "부담스러움" },
          { id: "o5", label: "매우 부담스러움" },
          { id: "o6", label: "해당 없음(교복 없음)" },
        ],
      },
      {
        id: "q2",
        type: "single",
        title: "학용품 구입 비용에 대해 어떻게 느끼십니까?",
        required: true,
        options: [
          { id: "o1", label: "전혀 부담되지 않음" },
          { id: "o2", label: "약간 부담" },
          { id: "o3", label: "보통" },
          { id: "o4", label: "부담스러움" },
          { id: "o5", label: "매우 부담스러움" },
        ],
      },
      {
        id: "q3",
        type: "single",
        title: "현장체험학습·수련회 등 행사 비용에 대해 어떻게 느끼십니까?",
        required: true,
        options: [
          { id: "o1", label: "전혀 부담되지 않음" },
          { id: "o2", label: "약간 부담" },
          { id: "o3", label: "보통" },
          { id: "o4", label: "부담스러움" },
          { id: "o5", label: "매우 부담스러움" },
        ],
      },
      {
        id: "q4",
        type: "multiple",
        title: "가장 부담이 되는 항목을 모두 선택해 주세요. (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "교복/체육복" },
          { id: "o2", label: "학용품·교과 부교재" },
          { id: "o3", label: "현장체험학습·수련회" },
          { id: "o4", label: "방과후 수강료" },
          { id: "o5", label: "급식비" },
          { id: "o6", label: "졸업앨범·기념품" },
        ],
      },
      { id: "q5", type: "likert5", title: "학교가 학습 준비물을 충분히 지원해 주고 있다고 느낍니다.", required: true, scale: SCALE },
      { id: "q6", type: "long", title: "교육 경비 부담 경감을 위해 학교나 교육청에 바라는 점을 적어주세요.", required: false },
    ],
    ["학부모", "비용", "부담"]
  ),
  // 27. 학원 사교육 의존도(가정 자가진단)
  t(
    "parent-27-private-edu-dependence",
    "학원 사교육 의존도 가정 자가진단",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교의 공교육 지원 방향 수립을 위해 가정의 사교육 실태를 익명으로 조사합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "현재 자녀가 다니고 있는 학원·과외의 개수는 몇 개입니까?",
        required: true,
        options: [
          { id: "o1", label: "0개" },
          { id: "o2", label: "1개" },
          { id: "o3", label: "2개" },
          { id: "o4", label: "3개" },
          { id: "o5", label: "4개 이상" },
        ],
      },
      {
        id: "q2",
        type: "single",
        title: "자녀의 주간 평균 사교육 시간은?",
        required: true,
        options: [
          { id: "o1", label: "받지 않음" },
          { id: "o2", label: "주 1~3시간" },
          { id: "o3", label: "주 4~6시간" },
          { id: "o4", label: "주 7~10시간" },
          { id: "o5", label: "주 10시간 이상" },
        ],
      },
      {
        id: "q3",
        type: "multiple",
        title: "사교육을 시키는 가장 큰 이유는 무엇입니까? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "학교 진도 보충" },
          { id: "o2", label: "선행 학습" },
          { id: "o3", label: "예체능·특기 교육" },
          { id: "o4", label: "친구들이 다녀서" },
          { id: "o5", label: "방과후 돌봄 목적" },
          { id: "o6", label: "진학 준비" },
        ],
      },
      {
        id: "q4",
        type: "single",
        title: "월평균 사교육비 부담은 어떻습니까?",
        required: true,
        options: [
          { id: "o1", label: "전혀 부담되지 않음" },
          { id: "o2", label: "약간 부담" },
          { id: "o3", label: "부담스러움" },
          { id: "o4", label: "매우 부담스러움" },
          { id: "o5", label: "해당 없음" },
        ],
      },
      { id: "q5", type: "likert5", title: "자녀가 사교육으로 인해 충분한 휴식·여가를 갖기 어렵다고 느낍니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "학교의 방과후·돌봄·보충학습이 사교육 부담 경감에 도움이 됩니다.", required: true, scale: SCALE },
      { id: "q7", type: "long", title: "공교육이 강화되었으면 하는 영역이 있다면 적어주세요.", required: false },
    ],
    ["학부모", "사교육", "공교육"]
  ),
  // 28. 학교운영위원회 인식·참여
  t(
    "parent-28-school-committee",
    "학교운영위원회 인식·참여 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교운영위원회 활성화를 위해 학부모님의 인식과 참여 의향을 조사합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "학교운영위원회의 역할·기능에 대해 알고 계십니까?",
        required: true,
        options: [
          { id: "o1", label: "매우 잘 알고 있다" },
          { id: "o2", label: "어느 정도 알고 있다" },
          { id: "o3", label: "들어본 적은 있다" },
          { id: "o4", label: "잘 모른다" },
        ],
      },
      { id: "q2", type: "likert5", title: "학교운영위원회 회의 결과·안건이 학부모에게 잘 안내됩니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "학교운영위원회가 학부모 의견을 잘 반영한다고 생각합니다.", required: true, scale: SCALE },
      {
        id: "q4",
        type: "single",
        title: "학교운영위원회 학부모 위원으로 참여할 의향이 있으십니까?",
        required: true,
        options: [
          { id: "o1", label: "매우 있다" },
          { id: "o2", label: "있다" },
          { id: "o3", label: "보통" },
          { id: "o4", label: "별로 없다" },
          { id: "o5", label: "전혀 없다" },
        ],
      },
      {
        id: "q5",
        type: "multiple",
        title: "학교운영위원회에서 가장 다루어 주었으면 하는 안건은? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "교육과정·평가" },
          { id: "o2", label: "급식 운영" },
          { id: "o3", label: "방과후 프로그램" },
          { id: "o4", label: "예산·시설" },
          { id: "o5", label: "안전·생활지도" },
          { id: "o6", label: "학교폭력 예방" },
        ],
      },
      { id: "q6", type: "long", title: "학교운영위원회 운영에 대한 건의사항을 적어주세요.", required: false },
    ],
    ["학부모", "학교운영위원회", "참여"]
  ),
  // 29. 학부모 자원봉사 의향
  t(
    "parent-29-volunteer-intent",
    "학부모 자원봉사 의향 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description: "학교 교육활동을 지원할 학부모 자원봉사 운영을 위해 의향을 조사합니다.",
        required: false,
      },
      {
        id: "q1",
        type: "single",
        title: "학부모 자원봉사에 참여할 의향이 있으십니까?",
        required: true,
        options: [
          { id: "o1", label: "매우 있다" },
          { id: "o2", label: "있다" },
          { id: "o3", label: "보통" },
          { id: "o4", label: "별로 없다" },
          { id: "o5", label: "전혀 없다" },
        ],
      },
      {
        id: "q2",
        type: "multiple",
        title: "참여하고 싶은 자원봉사 영역은? (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "녹색어머니회(교통지도)" },
          { id: "o2", label: "도서관 도우미" },
          { id: "o3", label: "급식 모니터링" },
          { id: "o4", label: "학교 행사 보조(운동회, 축제 등)" },
          { id: "o5", label: "독서·학습 도우미" },
          { id: "o6", label: "환경·녹색가꾸기" },
          { id: "o7", label: "안전 지킴이" },
        ],
      },
      {
        id: "q3",
        type: "single",
        title: "참여 가능한 빈도는 어떻습니까?",
        required: true,
        options: [
          { id: "o1", label: "주 1회 이상" },
          { id: "o2", label: "월 2~3회" },
          { id: "o3", label: "월 1회" },
          { id: "o4", label: "분기 1회" },
          { id: "o5", label: "필요시 비정기" },
        ],
      },
      {
        id: "q4",
        type: "single",
        title: "참여 가능한 시간대는?",
        required: true,
        options: [
          { id: "o1", label: "평일 오전" },
          { id: "o2", label: "평일 오후" },
          { id: "o3", label: "평일 저녁" },
          { id: "o4", label: "주말" },
        ],
      },
      {
        id: "q5",
        type: "single",
        title: "자원봉사 참여가 어려운 가장 큰 이유는?",
        required: false,
        options: [
          { id: "o1", label: "직장 근무" },
          { id: "o2", label: "동생 돌봄" },
          { id: "o3", label: "건강상 이유" },
          { id: "o4", label: "정보 부족" },
          { id: "o5", label: "기타" },
        ],
      },
      { id: "q6", type: "long", title: "자원봉사 운영에 대한 의견·건의사항을 자유롭게 적어주세요.", required: false },
    ],
    ["학부모", "자원봉사", "참여"]
  ),
  // 30. 자녀 정서·심리 가정 관찰
  t(
    "parent-30-emotional-observation",
    "자녀 정서·심리 가정 관찰 조사",
    "학부모만족도",
    [
      {
        id: "q0",
        type: "section",
        title: "안내드립니다",
        description:
          "자녀의 정서·심리 상태를 가정에서 관찰하신 내용을 토대로 응답해 주세요. 응답 결과는 학교 상담 및 정서 지원 계획에 활용되며 익명 처리됩니다.",
        required: false,
      },
      { id: "q1", type: "likert5", title: "자녀가 평소 밝고 즐거워 보입니다.", required: true, scale: SCALE },
      { id: "q2", type: "likert5", title: "자녀가 가족과의 대화를 자연스럽게 나눕니다.", required: true, scale: SCALE },
      { id: "q3", type: "likert5", title: "자녀가 자신의 감정을 잘 표현합니다.", required: true, scale: SCALE },
      { id: "q4", type: "likert5", title: "최근 자녀의 식욕·수면에 큰 변화가 없습니다.", required: true, scale: SCALE },
      { id: "q5", type: "likert5", title: "자녀가 짜증·분노·불안을 자주 표현하는 편입니다.", required: true, scale: SCALE },
      { id: "q6", type: "likert5", title: "자녀가 학교 가는 것을 부담스러워하지 않습니다.", required: true, scale: SCALE },
      {
        id: "q7",
        type: "multiple",
        title: "최근 자녀에게서 관찰되는 변화가 있다면 모두 선택해 주세요. (복수 선택)",
        required: false,
        options: [
          { id: "o1", label: "특별한 변화 없음" },
          { id: "o2", label: "말수가 줄어듦" },
          { id: "o3", label: "쉽게 짜증/화냄" },
          { id: "o4", label: "식욕 변화(증가/감소)" },
          { id: "o5", label: "수면 문제(불면/과수면)" },
          { id: "o6", label: "친구 관계 어려움 호소" },
          { id: "o7", label: "학교 가기 싫다고 함" },
          { id: "o8", label: "신체 증상 호소(두통, 복통 등)" },
        ],
      },
      {
        id: "q8",
        type: "single",
        title: "자녀에 대해 학교 상담(Wee클래스 등) 연계를 원하십니까?",
        required: false,
        options: [
          { id: "o1", label: "예, 원합니다" },
          { id: "o2", label: "추후 고려해 보겠습니다" },
          { id: "o3", label: "아니요, 필요하지 않습니다" },
        ],
      },
      { id: "q9", type: "long", title: "자녀의 정서·심리와 관련하여 담임 또는 상담 선생님께 알리고 싶은 내용이 있다면 적어주세요.", required: false },
    ],
    ["학부모", "정서", "심리"]
  ),
];
