import type { Template } from "@/lib/firebase/schema";

export const 학교폭력실태: Template = {
  id: "edu-school-violence",
  name: "학교폭력 실태조사",
  description: "교육부 학교폭력 실태조사 표준 양식 기반. 피해·가해·목격 경험 및 신고 의향을 확인합니다.",
  category: "학교폭력실태",
  source: "교육부",
  isOfficial: true,
  usageCount: 0,
  tags: ["학교폭력", "안전", "교육부", "필수조사"],
  questions: [
    {
      id: "q1",
      type: "single",
      title: "지난 학기(또는 최근 6개월) 동안 학교폭력 피해를 당한 경험이 있나요?",
      description: "학교폭력에는 신체 폭행, 욕설, 따돌림, 사이버 괴롭힘 등이 모두 포함됩니다.",
      required: true,
      options: [
        { id: "a", label: "전혀 없다" },
        { id: "b", label: "1~2번 있었다" },
        { id: "c", label: "3~5번 있었다" },
        { id: "d", label: "거의 매주 있었다" },
        { id: "e", label: "거의 매일 있었다" },
      ],
    },
    {
      id: "q2",
      type: "multiple",
      title: "피해를 당했다면 어떤 유형이었나요? (모두 선택, 없으면 건너뛰기)",
      required: false,
      options: [
        { id: "a", label: "언어폭력(욕설, 비방)" },
        { id: "b", label: "신체폭력(때리기, 밀치기 등)" },
        { id: "c", label: "집단 따돌림" },
        { id: "d", label: "사이버 괴롭힘(SNS, 메신저)" },
        { id: "e", label: "금품 갈취" },
      ],
    },
    {
      id: "q3",
      type: "single",
      title: "피해를 당한 장소는 주로 어디였나요?",
      required: false,
      options: [
        { id: "a", label: "교실 안" },
        { id: "b", label: "복도/계단/화장실" },
        { id: "c", label: "운동장/체육관" },
        { id: "d", label: "등하굣길" },
        { id: "e", label: "온라인(메신저/SNS/게임)" },
      ],
    },
    {
      id: "q4",
      type: "single",
      title: "피해 가해자는 주로 누구였나요?",
      required: false,
      options: [
        { id: "a", label: "같은 반 친구" },
        { id: "b", label: "같은 학년 다른 반 친구" },
        { id: "c", label: "선배" },
        { id: "d", label: "후배" },
        { id: "e", label: "잘 모르는 사람" },
      ],
    },
    {
      id: "q5",
      type: "single",
      title: "지난 학기 동안 다른 친구를 괴롭히거나 폭력을 행사한 적이 있나요?",
      required: true,
      options: [
        { id: "a", label: "전혀 없다" },
        { id: "b", label: "1~2번 있었다" },
        { id: "c", label: "3~5번 있었다" },
        { id: "d", label: "거의 매주 있었다" },
        { id: "e", label: "거의 매일 있었다" },
      ],
    },
    {
      id: "q6",
      type: "single",
      title: "다른 친구가 학교폭력을 당하는 것을 본 적이 있나요?",
      required: true,
      options: [
        { id: "a", label: "전혀 없다" },
        { id: "b", label: "1~2번 있었다" },
        { id: "c", label: "3~5번 있었다" },
        { id: "d", label: "거의 매주 있었다" },
        { id: "e", label: "거의 매일 있었다" },
      ],
    },
    {
      id: "q7",
      type: "single",
      title: "학교폭력을 목격했을 때 주로 어떻게 행동했나요?",
      required: false,
      options: [
        { id: "a", label: "선생님이나 어른께 알렸다" },
        { id: "b", label: "친구를 도와주거나 말렸다" },
        { id: "c", label: "그 자리를 피했다" },
        { id: "d", label: "모른 척했다" },
        { id: "e", label: "함께 동조하거나 구경했다" },
      ],
    },
    {
      id: "q8",
      type: "single",
      title: "학교폭력 피해를 당한다면 가장 먼저 누구에게 도움을 요청하겠습니까?",
      required: true,
      options: [
        { id: "a", label: "담임 선생님" },
        { id: "b", label: "부모님 또는 가족" },
        { id: "c", label: "친구" },
        { id: "d", label: "학교폭력 신고 117" },
        { id: "e", label: "아무에게도 말하지 않겠다" },
      ],
    },
    {
      id: "q9",
      type: "likert5",
      title: "우리 학교는 학교폭력 발생 시 적극적으로 대응한다고 생각한다.",
      required: true,
      scale: { min: 1, max: 5, labels: ["전혀 그렇지 않다", "그렇지 않다", "보통이다", "그렇다", "매우 그렇다"] },
    },
    {
      id: "q10",
      type: "likert5",
      title: "나는 학교에서 안전하다고 느낀다.",
      required: true,
      scale: { min: 1, max: 5, labels: ["전혀 그렇지 않다", "그렇지 않다", "보통이다", "그렇다", "매우 그렇다"] },
    },
    {
      id: "q11",
      type: "single",
      title: "학교폭력 예방 교육을 충분히 받고 있다고 생각하나요?",
      required: true,
      options: [
        { id: "a", label: "전혀 부족하다" },
        { id: "b", label: "부족한 편이다" },
        { id: "c", label: "보통이다" },
        { id: "d", label: "충분한 편이다" },
        { id: "e", label: "매우 충분하다" },
      ],
    },
    {
      id: "q12",
      type: "long",
      title: "학교폭력을 줄이기 위해 학교가 노력해야 할 점이나 하고 싶은 말을 자유롭게 적어주세요.",
      required: false,
    },
  ],
};
